data_analysis_task:
  description: >
    Continuously monitor and analyze market data for the selected stock ({stock_selection}).
    Use statistical modeling and machine learning to identify trends and predict market movements.
  expected_output: >
    Insights and alerts about significant market opportunities or threats for {stock_selection}.
  agent: data_analyst


strategy_development_task:
  description: >
    Develop and test various trading strategies based on insights from the Data Analyst Agent.
    Consider the user's risk tolerance and trading preferences.
  expected_output: >
    A set of potential trading strategies for {stock_selection} that align with the user's risk tolerance.
  agent: trading_strategy_agent


execution_planning_task:
  description: >
    Suggest optimal trade execution strategies based on approved trading strategies.
    Analyze timing, price, and logistical details of potential trades.
  expected_output: >
    Well-founded suggestions for when and how trades should be executed to maximize efficiency.
  agent: execution_agent


risk_assessment_task:
  description: >
    Evaluate and provide insights on the risks associated with potential trading activities.
    Scrutinize the risk exposure of proposed trades and suggest safeguards.
  expected_output: >
    A detailed analysis of risk exposure and recommendations for ensuring alignment with the firm's risk tolerance.
  agent: risk_management_agent